#!/usr/bin/env python3
import subprocess
subprocess.run(r"task add Read Taskwarrior documents later", shell=True)
subprocess.run(r"task add priority: H Pay bills", shell=True)
subprocess.run(r"task next", shell=True)
subprocess.run(r"task 2 done", shell=True)
subprocess.run(r"task", shell=True)
subprocess.run(r"task 1 delete", shell=True)
subprocess.run(r"task add Pay the rent due: eom", shell=True)
subprocess.run(r"task add Pay the rent Created task 12", shell=True)
subprocess.run(r"task 12 modify due: eom", shell=True)
subprocess.run(r"task 12 modify due:", shell=True)
subprocess.run(r"task add \"Five syllables here", shell=True)
subprocess.run(r"task entry.after: today-4days list", shell=True)
subprocess.run(r"task entry: yesterday list", shell=True)
subprocess.run(r"task entry.after: now-1hour list", shell=True)
subprocess.run(r"task end.after: 2015-05-0 and end.before: 2015-05-31 completed", shell=True)
subprocess.run(r"task end.after: today-1wk completed", shell=True)
subprocess.run(r"task project: This or project: That list", shell=True)
subprocess.run(r"task project: This and (priority: H or priority: M \) list", shell=True)
subprocess.run(r"task / pattern / list", shell=True)
subprocess.run(r"task rc.seach.case.sensitive: yes / pattern / list", shell=True)
subprocess.run(r"task rc.seach.case.sensitive: no / pattern / list", shell=True)
subprocess.run(r"task project: list", shell=True)
subprocess.run(r"task rc.report.next.sort = due-, urgency - next", shell=True)
subprocess.run(r"task add Rake the leaves project: 'Home & Garden'", shell=True)
subprocess.run(r"task project: OLDNAME modify project: NEWNAME", shell=True)
subprocess.run(r"task project: OLDNAME and status: pending modify project: NEWNAME", shell=True)
subprocess.run(r"task add project: Home.Kitchen Clean the floor", shell=True)
subprocess.run(r"task add project: Home.Kitchen Replace broken light bulb", shell=True)
subprocess.run(r"task add project: Home.Garden Plant the bulbs", shell=True)
subprocess.run(r"task project: Home.Kitchen count", shell=True)
subprocess.run(r"task project: Home.Garden count", shell=True)
subprocess.run(r"task project: Home count", shell=True)
subprocess.run(r"task projects", shell=True)
subprocess.run(r"task _projects", shell=True)
subprocess.run(r"task rc.list.all.projects = 1 projects", shell=True)
subprocess.run(r"task rc.list.all.projects = 1 _projects", shell=True)
subprocess.run(r"task _unique project", shell=True)
subprocess.run(r"task + home list", shell=True)
subprocess.run(r"task - home list", shell=True)
subprocess.run(r"task tags.any: list", shell=True)
subprocess.run(r"task + TAGGED list", shell=True)
subprocess.run(r"task tags.none: list", shell=True)
subprocess.run(r"task + this + that list", shell=True)
subprocess.run(r"task + this and +that list", shell=True)
subprocess.run(r"task + this or +that list", shell=True)
subprocess.run(r"task + this xor + that list", shell=True)
subprocess.run(r"task tags", shell=True)
subprocess.run(r"task rc.list.all.tags = 1 tags", shell=True)
subprocess.run(r"task _tags", shell=True)
subprocess.run(r"task 1 modify + next", shell=True)
subprocess.run(r"task due.after: yesterday and due.before: tomorrow list", shell=True)
subprocess.run(r"task + DUETODAY list", shell=True)
subprocess.run(r"task + DUE - DUETODAY list", shell=True)
subprocess.run(r"task + WEEK list", shell=True)
subprocess.run(r"task + OVERDUE list", shell=True)
subprocess.run(r"task 1 info", shell=True)
subprocess.run(r"task add Do the thing due: 2015-06-08T09: 00 recur: weekly", shell=True)
subprocess.run(r"task add Pay rent due: 28th recur: monthly until: now+1yr", shell=True)
subprocess.run(r"task config uda.priority.values H, M, , L", shell=True)
subprocess.run(r"task config uda.priority.values OMG, DoIt, Meh, Phfh, Nope,", shell=True)
subprocess.run(r"task 1 modify priority:", shell=True)
subprocess.run(r"task color", shell=True)
subprocess.run(r"task color legend", shell=True)
subprocess.run(r"task rc._forcecolor: on rc.defaultwidth: 120 rc.detection: off ...", shell=True)
subprocess.run(r"task _get 12.description", shell=True)
subprocess.run(r"task _get 12.entry 12.modified", shell=True)
subprocess.run(r"task _get tw.width tw.height", shell=True)
subprocess.run(r"task add Pay the rent due: eom wait: due-4days", shell=True)
subprocess.run(r"task add Buy wine for the party due: 12.due", shell=True)
subprocess.run(r"task _get 12.due.week", shell=True)
subprocess.run(r"task _get rc.report.next.columns", shell=True)
subprocess.run(r"task show report.next.columns", shell=True)
subprocess.run(r"task config default.command long", shell=True)
subprocess.run(r"task config default.command", shell=True)
subprocess.run(r"task config default.command ''", shell=True)
subprocess.run(r"task rc.default.command: long", shell=True)
subprocess.run(r"task show | grep report | grep sort", shell=True)
subprocess.run(r"task newest rc.verbose = nothing limit: 1 | cut - f1 - d' '", shell=True)
subprocess.run(r"task rc.verbose = nothing rc.report.foo.columns: id rc.report.foo.sort: id - foo limit: 1", shell=True)
subprocess.run(r"echo '{\"description\":\"A new task\"}' | task import -", shell=True)
subprocess.run(r"task add A new task", shell=True)
subprocess.run(r"task diagnostics", shell=True)
subprocess.run(r"task diagnostics | grep gnutls", shell=True)
subprocess.run(r"task 12 edit", shell=True)
subprocess.run(r"EDITOR = vim task 12 edit", shell=True)
subprocess.run(r"task rc.report.list.filter: list", shell=True)
subprocess.run(r"task all", shell=True)
